{
  "extends": "standard",
  "env": {
    "browser": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "globals": {
    # key = global variable name
    # value = allow the variable to be overwritten - true / false
    "$": false,
    "jQuery": false,
    "_": false
  },
  "rules": {
    "semi": ["error", "always"],
    "space-before-function-paren": ["error", "never"]
  }
}
